security:
    encoders:
        App\Entity\Account:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: App\Entity\Account
        in_memory: { memory: ~ }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~
            provider: db_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: dashboard
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
